### ISSUE TITLE
LVDS display

### ISSUE THREAD

**Issue by JonathanConstant** [rafaello7/linux-nanopi-m3#3]
Hello Rafaello,
First, thanks a lot for your great work !
I am trying to configure the kernel for LVDS display but I am missing something.
I enabled LVDS in menuconfig but it still boot only with HDMI.
I think I need to enter my lvds screen parameters somewhere and change HDMI to LVDS at boot. 
Could you help for this ? 
Thank you.

**Comment by rafaello7** [comment]
Some settings are needed [in dts file](https://github.com/rafaello7/linux-nanopi-m3/blob/master/arch/arm64/boot/dts/nexell/s5p6818-nanopi-m3.dts). One entry with _dp_drm_lvds_ should be added and _panel: panel-simple_ entry should be modified. Please compare with [settings for SamsungARTIK](https://github.com/SamsungARTIK/linux-artik/tree/A710/v4.4/arch/arm64/boot/dts/nexell). Probably setting for LVDS should be similar to below:

	dp_drm_lvds: display_drm_lvds {
            remote-endpoint = <&lvds_panel>;
			status = "ok";

			dp_control {
				clk_src_lv0 = <3>;
				clk_div_lv0 = <16>;    -- value depends on panel, on 3.x board it is calculated
				clk_src_lv1 = <7>;
				clk_div_lv1 = <1>;
				out_format = <3>;
			};
		};

Artik boards have _panel-simple_ settings with _compatible = "dongguan,gst7d0038";_. I don't know whether it is right for NanoPi.

**Comment by JonathanConstant** [comment]
Thanks for your answer, I followed your advices but it still only boots with HDMI. I will keep searching and inform you if I get it working.

**Comment by rafaello7** [comment]
Are there any errors in dmesg output?

When X windows are running, is the panel visible in display settings?

**Comment by JonathanConstant** [comment]
No errors, I have [drm] Load HDMI panel at 1.80 seconds
I ddidn't install X, I just have the console.

**Comment by rafaello7** [comment]
Have you added entry for panel-simple? I see that driver for panel-simple differs between version 4.4 and 4.11. At least the _dongguan,gst7d0038_ driver does not exist in 4.11 kernel. Probably you will need to modify the [panel-simple.c](https://github.com/rafaello7/linux-nanopi-m3/blob/master/drivers/gpu/drm/panel/panel-simple.c) file. See [panel-simple.c in kernel 4.4](https://github.com/SamsungARTIK/linux-artik/blob/A710/v4.4/drivers/gpu/drm/panel/panel-simple.c).

**Comment by JonathanConstant** [comment]
Yes I added my config in panel-simple.c

```
// Add panel lvds nanopi
static const struct drm_display_mode nanopi_lvds7p_mode = {
	.clock = 33300,
	.hdisplay = 800,
	.hsync_start = 800+210,
	.hsync_end = 800+210+20,
	.htotal = 800+210+20+46,
	.vdisplay = 480,
	.vsync_start = 480+22,
	.vsync_end = 480+22+10,
	.vtotal = 480+22+10+23,
	.vrefresh = 60,
}; 

static const struct panel_desc nanopi_lvds7p = {	
	.modes = &nanopi_lvds7p_mode,
	.num_modes = 1,
	.size = {
		.width = 800,
		.height = 480,
	},	
};

       {
	.compatible = "nanopi,lvds7p",
	.data = &nanopi_lvds7p,
	}, 
```

It seems that the compilation of the kernel didn't work, I added comments and it does not appear during boot in dmesg. 
For the kernel compilation, after the make, I copy the Image /arch/arm64/boot/Image in my SD card over the old image:
`cp arch/arm64/boot/Image /media/jonathan/EECA-0605/vmlinuz `
Is it the right procedure ? 

Thanks,

**Comment by rafaello7** [comment]
The Image.gz should be copied, not _Image_.

**Comment by JonathanConstant** [comment]
Ok, I cleaned my sd card and reinstalled kernel and uboot with your debian-installer with only one partition. Now I can boot on LVDS (my display does not work yet) : dmesg errors 
```
[    1.788000] panel-simple panel: panel supply power not found, using dummy regulator
[    1.796000] panel-simple panel: failed to request GPIO: -16
[    1.800000] panel-simple: probe of panel failed with error -16
```
But now I can move on. Thank you !

**Comment by JonathanConstant** [comment]
Thank you very much rafaello for your help. Now it's working !!!!

**Comment by rafaello7** [comment]
Could you give a patch? The _git diff_ output or so. I add this change to kernel.

**Comment by JonathanConstant** [comment]
Here is the diff of panel-simple.c and s5p6818-nanopi-m3.dts
[lvds_diff.zip](https://github.com/rafaello7/linux-nanopi-m3/files/1337899/lvds_diff.zip)

**Comment by rafaello7** [comment]
With these changes I have Linux console output in upper left corner. In GUI settings I see two displays. It looks the LVDS panel (non-) existence is not recognized by Linux kernel.

I will need to add some kernel parameter to turn on/off the panel. I see in kernel 3.x there is a parameter named _lcd_. I think the parameter may be inherited. I see a few 800x480 panels in 3.x kernel settings: S70, S702, S70D, W50, S430. Which one you have?

**Comment by JonathanConstant** [comment]
I don't have the Friendlyarm panels, I have a 7inch atops lvds display. In the menuconfig I had to enable:
 -> Device Drivers                                                                                                                                                                                                                                                                                                                                                                                                    
      -> Graphics support                                                                                                                                                                                                                                                                                                                                                                                                 
            -> DRM Support for NEXELL Display Controller (DRM_NX [=y])     
And also:
 -> Device Drivers                                                                                                                                                                                                                                                                                                                                                                                                    
      -> Graphics support  
           -> Display panels
                  -> support for simple panels

**Comment by rafaello7** [comment]
How did you use the display with 3.x kernel? Did you build custom kernel with settings for your lvds or did you utilize one of the settings for FriendlyARM panels?

I'm thinking about adding the lvds/rgb panels support in the kernel. Probably I add two parameters in kernel, one for the lvds output and one for rgb. I prepare changes and give you for testing. OK?

**Comment by JonathanConstant** [comment]
with 3.x kernel, I build custom kernel with my settings (lvds timing and resolution) and I forced the boot with LVDS, by defaults it boots only on friendlyarm lcd panel or HDMI. No problem, I can test your changes. 

I have another question about the kernel version. I have a problem with linux 4.11 for installing some USB BT and Wifi drivers, I tried to install linux 4.4 from Samsung artik : https://github.com/SamsungARTIK/linux-artik/tree/A710/v4.4 but it does not work, when I power on the board, it does not load the kernel and reboots. I added the nanopim3_defconfig file and also s5p6818-nanopi-m3.dts. 
After the make, Image.gz and  s5p6818-nanopi-m3.dtb are created but I have modules errors like:
```
 Building modules, stage 2.
  MODPOST 25 modules
ERROR: "DrvMSleep" [drivers/media/platform/nxp-vpu/nx_vpu_v4l2.ko] undefined!
ERROR: "VPU_SWReset" [drivers/media/platform/nxp-vpu/nx_vpu_v4l2.ko] undefined!
ERROR: "vb2_buffer_done" [drivers/media/platform/nxp-vpu/nx_vpu_v4l2.ko] undefined!
ERROR: "vb2_streamoff" [drivers/media/platform/nxp-vpu/nx_vpu_v4l2.ko] undefined!
ERROR: "vb2_streamon" [drivers/media/platform/nxp-vpu/nx_vpu_v4l2.ko] undefined!
ERROR: "vb2_querybuf" [drivers/media/platform/nxp-vpu/nx_vpu_v4l2.ko] undefined!
```
I just put few errors but there is at least 50 like that.

**Comment by rafaello7** [comment]
You can disable "Nexell Video Codec" driver compilation. This is a driver for VPU, Video Processing Unit (coda960). Unless you want to compile GStreamer plugins from Artik to play video... The driver is in menuconfig in "Device Drivers" -> "Multimedia support".

What drivers you need? Maybe I will be able o help you.

**Comment by JonathanConstant** [comment]
Ok thanks. 
I need the realtek driver rtk_btusb.ko. In linux 4.11 the driver is already installed but not working. I can see the bluetooth device however running hcitool scan and hcitool lescan returns no devices found.Same thing with bluetoothctl command. hciconfig hci0 is up and systemctl status bluetooth is started. 
I tried to disable realtek bluetooth drivers compilation and install it manually but I get the same result.

**Comment by JonathanConstant** [comment]
Now I don't have these errors anymore when compiling linux 4.4 but it does not start. Boot stays blocked at starting kernel. I also tried with linux 4.1 and same result. Do you know what is the problem ? Your u-boot version can only work with linux 4.11 ?

**Comment by rafaello7** [comment]
Have you compiled original kernel from Artik? It is problematic. I have fixed a few bugs in it to boot it up. Try to apply this patch: [patch-v4.4.gz](https://github.com/rafaello7/linux-nanopi-m3/files/1341777/patch-v4.4.gz) I hope it helps.

**Comment by rafaello7** [comment]
I have two questions concerning your patch:
1. You have set _out_format_ parameter value in "dts" file to &lt;2&gt;. Does the format value make a difference? Is the panel still working with the format set to 3 ?
2. You have clk_div_lv0 set to 16. According to my calculations, with this divider your panel works at refresh rate 90 Hz. In dts for Artik the value of 16 is set for gst7d0038, which, as I see in simple-panel.c, has 1024x600 resolution. The divider value should be calculated according to formula:

      pll / (htotal * vtotal * vrefresh)

Where pll is frequency of pll clock chosen by clk_src_lv0 parameter. The value of 0 choses pll0, which is 800 MHz. BTW  the _htotal * vtotal * vrefresh_ should match _clock_ value in _drm_display_mode_  structure (given in kHz).

Could you set the clk_div_lv0 value to 24 and check whether your panel is still working?

**Comment by JonathanConstant** [comment]
- For the kernel 4.4, unfortunately your patch didn't help, the kernel is not loaded and the pi doesn't stop to reboot. 
I will try to figure it out this afternoon.

- For the lvds:
1- The panel is still working with the format set to 3.
2- It is also still working with clk_div_lv0 to 24. 
As I am working only with the console I don't see really improvements. I will adjust the parameters later with my application running when I install Qt, but now I am focused on this bluetooth driver that is not working and that is really problematic :/

**Comment by rafaello7** [comment]
Maybe you have enabled Artik TEE (CONFIG_ARTIK_TRUSTZONE_DRIVER). Please disable it. If you are compiling bl1 loader, you can also comment out boardReset() call in src/psci.c file, in psciHandler function. Set result to -1 instead. Probably this reset is done in response to the Artik TEE system call. You can use the patch below:

	diff --git a/src/psci.c b/src/psci.c
	index 1bc040a..d2de8c8 100644
	--- a/src/psci.c
	+++ b/src/psci.c
	@@ -86,7 +86,8 @@ void psciHandler(unsigned long *regs)
			 break;
		 default:
			 printf("psciHandler FATAL: unknown function %x\r\n", regs[0]);
	-        boardReset();
	+               result = -1;
	+        //boardReset();
		 }
		 regs[0] = result;
	 }

Unfortunately I can't help you with the BT dongle, I have no experience with realtek bluetooth.

As of LVDS, I wanted to ask you the questions because I'm trying to prepare general solution, to support also other panels. The divider value will be calculated and in case of your panel will be set to 24. Also I wanted to know how important is _out_format_ value, whether I need to set the value to 2 for your panel.

**Comment by JonathanConstant** [comment]
Nice !! It boots now, I disable CONFIG_ARTIK_TRUSTZONE_DRIVER.
But there is still a problem at the end of the boot: 
```
Missing modules (car /proc/modules; ls /dev)
/dev/mmcblk2p2 does not exist
```
ls /dev shows , mmcblk0, mmcblk0p1, mmcblk0p2

I am sorry, I am really a noob with uboot and linux kernel. I used your debian-installer, I think I need to mount mmcbclk0 and not mmcblk2 but how could I change that ? I can't copy the u-boot.bin and apply 
`dd if=u-boot.bin of=/dev/mmcblk0 seek=65 `

Thanks !

**Comment by rafaello7** [comment]
No problem. I spent half of my life on programming, please do not compare with mine ;)

I guess you haven't access to u-boot console through debug serial port. In this case you need to compile [ubootenv tool](https://github.com/rafaello7/debian-installer-nanopi-m3/tree/master/ubootenv). Next, take the script below (it assumes the ubootenv is on $PATH). Modify variables at the script beginning and run:

	#!/bin/sh -e
	loadcmd="ext4load mmc 0:1"  # fatload if /boot is on fat filesystem, ext4load if ext2/ext3/ext4
								# "mmc 0:1" when boot is on first partition, 0:2 when on second and so on
	bootpath=                   # empty when boot is a separate mount, "boot/" if plain directory
	rootmnt=/dev/mmcblk0p2      # root parameter for NanoPi
	embed_drv=/dev/sde          # SD card to modify


	type ubootenv
	right='bootargs=console=ttySAC0,115200n8 initrd=0x49000000,0x800000 roo'
	cur="$(dd if="$embed_drv" bs=4 skip=131073 count=16 status=none)"
	if [ "$cur" != "$right" ]; then
		echo "Selected drive doesn't seem to have NanoPi Debian installation."
		read -p "Continue anyway (Y/N) [N] ? " ans
		[ "$ans" = y -o "$ans" = Y ] || exit
	fi

	{
		echo "bootargs=console=ttySAC0,115200n8 initrd=0x49000000,0x800000 root=$rootmnt console=tty1"
		echo "bootcmd=$loadcmd 0x49000000 ${bootpath}vmlinuz; unzip 0x49000000 0x48000000; mw 0x49000000 0 0x800000; $loadcmd 0x49000000 ${bootpath}initrd.img; $loadcmd 0x4a000000 ${bootpath}s5p6818-nanopi-m3.dtb; booti 0x48000000 - 0x4a000000"
	} | ubootenv | dd of="$embed_drv" bs=1k seek=512

The u-boot environment is at 512-kB offset of the SD card. It has some special format and contains a checksum.

**Comment by JonathanConstant** [comment]
Oh I am stupid, I could access to u-boot console with my arduino and now it boots correctly. Great !! Thank you a lot for your help. Now I just have to test again the bluetooth driver if it works and if not, I will test the linux 4.1 :/ .

**Comment by rafaello7** [comment]
If you would find some time to check whether [this kernel image](https://drive.google.com/file/d/0B8m_JgFBfEzwcU5CMzVWeTE4VU0/view?usp=sharing) works with your panel, it would be great. I have confirmation that it works with one of LCD panels. I have customized slightly this kernel, it has set kernel parameter value set for your lvds panel. Normally the kernel image will need kernel param _panel-nanopi.lvds=atops_.
The kernel has to be installed from running Debian on NanoPi, using _dpkg -i_ command. Simply run as root:

    dpkg -i linux-image-4.11.6+_4.11.6+-6_arm64.deb

The new kernel will be installed as /boot/vmlinuz-4.11.6+. Also the "dtb" file will be installed as /boot/s5p6818-nanopi-m3.dtb. Ensure that /boot/vmlinuz is a symbolic link which points to /boot/vmlinuz-4.11.6+. Finally, reboot.

**Comment by JonathanConstant** [comment]
That's good, your kernel image works with my lvds panel.

**Comment by JonathanConstant** [comment]
Finally I could install the drivers for my BT/Wifi dongle with the kernel 4.4. Thank you very much for your help. 
One last thing, I am trying to cross compile Qt and I need Mali driver. Do you know how I can get it ?

**Comment by rafaello7** [comment]
You mean: mali driver in kernel? The 4.4 kernel has it in kernel tree, _drivers/gpu/arm_. I have also ported it recently to 4.11, but it needs to be enabled in kernel config. Although I don't know whether the ported driver works, I don't know how to test it.

I see a worse problem, namely I don't have any userland library which would work with the Mali GPU. Have you any? This is also the reason why the driver was not tested by me.

**Comment by JonathanConstant** [comment]
Yes, I mean the mali driver in kernel. I tested mali drivers with kernel 4.4 but it does not work with Qt. 
You could test the Mali GPU with Qt but you have to to cross-compile it and it's a lot of work and time for the compilation.. I don't know other ways for testing the Mali drivers. If you want to do that I can give you the steps.  
I need mali MP2 drivers as I compile with aarch64. There is some open source drivers like sunxi-mali but it compiles only for 32bits.

**Comment by rafaello7** [comment]
If the library does not work on kernel 4.4, there is rather no reason to work on 4.11.

Qt is a higher level library, it must use other, low-level libraries dedicated for the graphics card - libEGL.so, libGLESv2.so. They aren't open-source and, as I know, are distributed by ARM only in binary form. [For some platforms they are freely available](https://developer.arm.com/products/software/mali-drivers/user-space), but I haven't found any 64-bit for Mali 400. Without these libraries there is no chance for accelerated GLES.

**Comment by JonathanConstant** [comment]
Hi Rafaello,
I am sorry I need your help again. As I can't find 64-bit Mali 400 drivers, I am trying to compile the kernel 4.4 in 32-bit and use it with u-boot of FriendlyArm. The kernel compiled without error but the u-boot stays blocked at "Starting kernel". 
I also tried to compile your u-boot in 32-bit but this time it didn't boot anymore.. 
Do you know these issues ? 
Hope you can help.

**Comment by rafaello7** [comment]
I did never run the kernel in 32-bit mode.

I have tested now to run, with the same effect as yours. It looks the kernel hangs early at startup. The Linux code is started, but hangs quickly, possibly at MMU enable. I have disabled in u-boot (from FriendlyArm) an option which enables MMU in it and replaced in kernel sources _head.S_ file containig kernel startup code (arch/arm/kernel/head.S) with such from 3.x kernel but with no effect. Although after those changes the kernel does not hang completely - the board is reset instead. It looks a lot of effort would be needed to run the kernel.

I see in _arch/arm_ directory a board-specific directory for s5p4418 board (mach-s5p4418) but for s5p6818 a similar directory does not exist. Probably the kernel was never prepared to run with s5p6818 in 32-bit mode.

**Comment by JonathanConstant** [comment]
Ok thank you very much for your effort. You are right it seems to be a lot of work to get it working ! Finally, yesterday I could installed my drivers for my BT/Wifi dongle in the kernel 3.4, so I will stay with this EOL linux version, it's the easier solution. Thanks again for your help.
